require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.0
  TargetRailsVersion: 5.2.4.3
  Exclude:
    - "node_modules/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "config/**/*"
    - "app/channels/**/*"
    - "bin/*"
    - "app/mailers/*"
    - "db/migrate/*"
    - "app/uploaders/*"
    - "db/schema.rb"
    - "spec/spec_helper.rb"
    - "spec/rails_helper.rb"
    - "Gemfile"
    - "Rakefile"
    - "config.ru"

# 日本語のコメントを許可
Style/AsciiComments:
  Enabled: false

# classの説明コメントは不要
Style/Documentation:
  Enabled: false

# フローズンリテラルコメントは不要
Style/FrozenStringLiteralComment:
  Enabled: false

# デフォルトをダブルクォーテーションに指定 
Style/StringLiterals:
  EnforcedStyle: double_quotes

# シンボル、配列は%記法ではなく、[]を使用
Style/SymbolArray:
  EnforcedStyle: brackets

# デフォルトをコンパクトスタイルに指定
Style/ClassAndModuleChildren:
  EnforcedStyle: compact

# 可読性を向上する為のスペースは許容
Layout/ExtraSpacing:
  Enabled: false

Layout/LineLength:
  Max: 150
  Exclude:
    - "db/seeds.rb"

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 25
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 15
