inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'config/**/*'
    - 'app/channels/**/*'
    - 'bin/*'
    - 'app/mailers/*'
    - 'db/schema.rb'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# hash書き方の指定
Style/HashSyntax:
  EnforcedStyle: ruby19

# classの説明コメントは不要とする
Style/Documentation:
  Enabled: false

# フローズンリテラルコメントは不要とする
Style/FrozenStringLiteralComment:
  Enabled: false

# selfは許容する
Style/RedundantSelf:
  Enabled: false

# デフォルトはダブルクォーテーション 
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/BlockComments:
  Enabled: false

# コンパクトスタイルをデフォルトにする
Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Layout/CommentIndentation:
  Enabled: false

# スペースがあった方が見やすい
Layout/ExtraSpacing:
  Enabled: false

Layout/LineLength:
  Max: 150

Lint/NonDeterministicRequireOrder:
  Enabled: false

# gemは並び替えない
Bundler/OrderedGems:
  Enabled: false
