inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'db/schema.rb'

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# hash書き方の指定
Style/HashSyntax:
  EnforcedStyle: ruby19

# gemは並び替えない
Bundler/OrderedGems:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

# スペースがあった方が見やすい
Layout/ExtraSpacing:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false